package main

import (
	"log"

	_ "github.com/carlosveg/go_test/docs"

	"github.com/carlosveg/go_test/services"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/swagger"
	// _ "github.com/swaggo/fiber-swagger/example/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title			Prueba GO
// @version		1.0
// @description	Prueba GOLANG
// @termsOfService	http://swagger.io/terms/
func main() {
	app := fiber.New()

	app.Get("/swagger/*", swagger.HandlerDefault)

	app.Get("/", services.ListUsers)
	app.Post("/", services.AddUser)
	app.Post("/login", services.Login)

	err := app.Listen(":3001")

	if err != nil {
		log.Fatalf("fiber.Listen failed %s", err)
	}
}
